
import { PrismaClient, UserRole, UserStatus, Gender, AppointmentStatus } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
    console.log('🧪 Starting verification data insertion...');

    const timestamp = Date.now();
    const password = 'Password123!';
    const hashedPassword = await bcrypt.hash(password, 10);

    // 1. Create a specific Verification Doctor
    const doctorEmail = `verify.doctor.${timestamp}@saiphani.com`;
    console.log(`Creating Doctor: ${doctorEmail}`);

    const doctorUser = await prisma.user.create({
        data: {
            email: doctorEmail,
            passwordHash: hashedPassword,
            role: UserRole.DOCTOR,
            status: UserStatus.ACTIVE,
            staff: {
                create: {
                    firstName: 'Verification',
                    lastName: `Doctor ${timestamp}`,
                    phone: `9${timestamp.toString().slice(-9)}`, // ensure unique phone
                    specialization: 'System Test',
                    department: 'IT',
                    licenseNo: `TEST-${timestamp}`,
                },
            },
        },
        include: { staff: true },
    });

    // 2. Create a Verification Patient
    const patientEmail = `verify.patient.${timestamp}@saiphani.com`;
    const uhid = `UHID-TEST-${timestamp}`;
    console.log(`Creating Patient: ${patientEmail} (UHID: ${uhid})`);

    const patientUser = await prisma.user.create({
        data: {
            email: patientEmail,
            passwordHash: hashedPassword,
            role: UserRole.PATIENT,
            status: UserStatus.ACTIVE,
            patient: {
                create: {
                    firstName: 'Verification',
                    lastName: `Patient ${timestamp}`,
                    uhid: uhid,
                    dateOfBirth: new Date('1990-01-01'),
                    gender: Gender.MALE,
                    phone: `8${timestamp.toString().slice(-9)}`,
                    address: '123 Verification Lane',
                    bloodGroup: 'O+',
                },
            },
        },
        include: { patient: true },
    });

    if (!doctorUser.staff || !patientUser.patient) {
        throw new Error('Failed to create relations');
    }

    // 3. Create an Appointment
    console.log('Creating Test Appointment...');
    const appointment = await prisma.appointment.create({
        data: {
            patientId: patientUser.patient.id,
            doctorId: doctorUser.staff.id,
            scheduledAt: new Date(Date.now() + 1000 * 60 * 60), // 1 hour from now
            duration: 30,
            status: AppointmentStatus.CONFIRMED,
            reason: 'Database Verification Check',
            notes: 'Generated by verification script',
        },
    });

    console.log('------------------------------------------------');
    console.log('✅ VERIFICATION DATA INSERTED SUCCESSFULLY');
    console.log('------------------------------------------------');
    console.log('Look for these records in pgAdmin:');
    console.log(`1. Table: "users"`);
    console.log(`   - Email: ${doctorEmail}`);
    console.log(`   - Email: ${patientEmail}`);
    console.log(`2. Table: "patients"`);
    console.log(`   - UUID: ${patientUser.patient.id}`);
    console.log(`   - Name: Verification Patient ${timestamp}`);
    console.log(`3. Table: "appointments"`);
    console.log(`   - ID: ${appointment.id}`);
    console.log('------------------------------------------------');
}

main()
    .catch((e) => {
        console.error(e);
        process.exit(1);
    })
    .finally(async () => {
        await prisma.$disconnect();
    });
